# Generated by Django 5.2.6 on 2025-09-08 21:08

import django.db.models.deletion
import trades.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=100)),
                ('option_strike_price_expiry', models.CharField(max_length=100)),
                ('option_buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('intraday_exit_price_target', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stop_loss_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('support_level', models.CharField(max_length=100)),
                ('resistance_level', models.CharField(max_length=100)),
                ('capital_required', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_loss_if_stop_loss_hits', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_profit_if_target_hits', models.DecimalField(decimal_places=2, max_digits=10)),
                ('news_catalyst_summary', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('stock_name', 'option_strike_price_expiry', 'option_buy_price', 'intraday_exit_price_target', 'stop_loss_price', 'support_level', 'resistance_level', 'capital_required', 'news_catalyst_summary'), name='uniq_trademaster_all_fields_except_user_status')],
            },
        ),
        migrations.CreateModel(
            name='TradeProfitLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_or_loss', models.CharField(blank=True, choices=[('Profit', 'Profit'), ('Loss', 'Loss')], max_length=10, null=True)),
                ('profit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loss_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ttpl_created', to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pls', to='trades.trademaster')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ttpl_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Account summary',
                'verbose_name_plural': 'Account summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trades.tradeprofitloss',),
        ),
        migrations.CreateModel(
            name='TradeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('is_ai_correct', models.BooleanField(default=False)),
                ('profit_or_loss', models.CharField(choices=[('Profit', 'Profit'), ('Loss', 'Loss')], max_length=10)),
                ('profit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('loss_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpl_created', to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(limit_choices_to=trades.models.tm_choices_today, on_delete=django.db.models.deletion.CASCADE, to='trades.trademaster')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tpl_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='tradeprofitloss',
            constraint=models.UniqueConstraint(fields=('trade', 'created_by'), name='uniq_tpl_trade_user'),
        ),
        migrations.AddConstraint(
            model_name='tradeprofitloss',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('profit_or_loss', 'Profit'), ('profit_amount__isnull', False), ('loss_amount__isnull', True)), models.Q(('profit_or_loss', 'Loss'), ('loss_amount__isnull', False), ('profit_amount__isnull', True)), models.Q(('profit_or_loss__isnull', True), ('profit_amount__isnull', True), ('loss_amount__isnull', True)), models.Q(('profit_or_loss', ''), ('profit_amount__isnull', True), ('loss_amount__isnull', True)), _connector='OR'), name='tpl_valid_profit_loss_amounts'),
        ),
    ]
