# Generated by Django 3.2.25 on 2025-09-06 17:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=100)),
                ('option_strike_price_expiry', models.CharField(max_length=100)),
                ('option_buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('intraday_exit_price_target', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stop_loss_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('support_level', models.CharField(max_length=100)),
                ('resistance_level', models.CharField(max_length=100)),
                ('capital_required', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_loss_if_stop_loss_hits', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_profit_if_target_hits', models.DecimalField(decimal_places=2, max_digits=10)),
                ('news_catalyst_summary', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('profit_or_loss', models.CharField(blank=True, choices=[('Profit', 'Profit'), ('Loss', 'Loss')], max_length=10, null=True)),
                ('profit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loss_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpTradeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('is_ai_correct', models.BooleanField(default=False)),
                ('profit_or_loss', models.CharField(choices=[('Profit', 'Profit'), ('Loss', 'Loss')], max_length=10)),
                ('trade', models.ForeignKey(limit_choices_to={'created_at': datetime.date(2025, 9, 6)}, on_delete=django.db.models.deletion.CASCADE, to='trades.trademaster')),
            ],
        ),
    ]
