# Generated by Django 3.2.25 on 2025-09-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trademaster',
            constraint=models.UniqueConstraint(fields=('stock_name', 'option_strike_price_expiry', 'option_buy_price', 'intraday_exit_price_target', 'stop_loss_price', 'support_level', 'resistance_level', 'capital_required', 'max_loss_if_stop_loss_hits', 'max_profit_if_target_hits', 'news_catalyst_summary'), name='uniq_trademaster_all_fields_except_user_status'),
        ),
    ]
