# Generated by Django 3.2.25 on 2025-09-07 04:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_trademaster_uniq_trademaster_all_fields_except_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('is_ai_correct', models.BooleanField(default=False)),
                ('profit_or_loss', models.CharField(choices=[('Profit', 'Profit'), ('Loss', 'Loss')], max_length=10)),
                ('trade', models.ForeignKey(limit_choices_to={'created_at': datetime.date(2025, 9, 7)}, on_delete=django.db.models.deletion.CASCADE, to='trades.trademaster')),
            ],
        ),
        migrations.DeleteModel(
            name='UpTradeTransaction',
        ),
    ]
