# Generated by Django 3.2.25 on 2025-09-07 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0003_auto_20250907_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeProfitLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_or_loss', models.CharField(blank=True, choices=[('Profit', 'Profit'), ('Loss', 'Loss')], max_length=10, null=True)),
                ('profit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loss_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpl_created', to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pls', to='trades.trademaster')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tpl_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='tradeprofitloss',
            constraint=models.UniqueConstraint(fields=('trade', 'created_by'), name='uniq_tpl_trade_user'),
        ),
        migrations.AddConstraint(
            model_name='tradeprofitloss',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('profit_or_loss', 'Profit'), ('profit_amount__isnull', False), ('loss_amount__isnull', True)), models.Q(('profit_or_loss', 'Loss'), ('loss_amount__isnull', False), ('profit_amount__isnull', True)), models.Q(('profit_or_loss__isnull', True), ('profit_amount__isnull', True), ('loss_amount__isnull', True)), models.Q(('profit_or_loss', ''), ('profit_amount__isnull', True), ('loss_amount__isnull', True)), _connector='OR'), name='tpl_valid_profit_loss_amounts'),
        ),
    ]
