# Generated by Django 3.2.25 on 2025-09-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_auto_20250907_1030'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trademaster',
            name='uniq_trademaster_all_fields_except_user_status',
        ),
        migrations.RemoveField(
            model_name='trademaster',
            name='loss_amount',
        ),
        migrations.RemoveField(
            model_name='trademaster',
            name='profit_amount',
        ),
        migrations.RemoveField(
            model_name='trademaster',
            name='profit_or_loss',
        ),
        migrations.AddConstraint(
            model_name='trademaster',
            constraint=models.UniqueConstraint(fields=('stock_name', 'option_strike_price_expiry', 'option_buy_price', 'intraday_exit_price_target', 'stop_loss_price', 'support_level', 'resistance_level', 'capital_required', 'news_catalyst_summary'), name='uniq_trademaster_all_fields_except_user_status'),
        ),
    ]
