# Generated by Django 3.2.25 on 2025-09-07 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0005_auto_20250907_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradetransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradetransaction',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tpl_created', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradetransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tradetransaction',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tpl_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tradeprofitloss',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ttpl_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tradeprofitloss',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ttpl_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
