# Generated by Django 3.2.25 on 2025-09-07 11:30

from django.db import migrations, models
import django.db.models.deletion
import trades.models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0006_auto_20250907_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradetransaction',
            name='loss_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tradetransaction',
            name='profit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='tradetransaction',
            name='trade',
            field=models.ForeignKey(limit_choices_to=trades.models.tm_choices_today, on_delete=django.db.models.deletion.CASCADE, to='trades.trademaster'),
        ),
    ]
